# Generated by Django 4.2.4 on 2023-08-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authentications",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_xid", models.CharField(max_length=50)),
                ("token", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_xid", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Deposits",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("deposit_by", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("ENABLED", "enabled"), ("DISABLED", "disabled")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("deposit_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.IntegerField(default=0)),
                ("reference_id", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Wallets",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("owned_by", models.CharField(max_length=50, unique=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("ENABLED", "enabled"), ("DISABLED", "disabled")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("balance", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Withdrawals",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("withdrawn_by", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("ENABLED", "enabled"), ("DISABLED", "disabled")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.IntegerField(default=0)),
                ("reference_id", models.CharField(max_length=50)),
            ],
        ),
    ]
